# Site settings
baseURL = "https://kzeezclothing.com"
languageCode = "en-US"
title = "KZeez Clothing"
# theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2025 Walker Tubb"

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "KZees Clothing"
  description = "Women and Men's apperal, modern, vintage and live auctions"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Whether you purchased the license from the author.
  licensed = true

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = false
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = true
      mute = true
     # file = "videos/background.mp4"
       youtubeId = "Sg35CYuU_-A"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Ways to Shop"

      [[params.links.list1.link]]
        text = "WhatNot"
        url = "#"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Online Store"
        url = "#"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = "Posh Mark"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "#"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "#"

      [[params.links.list2.link]]
        text = "Dribbble"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Link One"
        url = "#"

      [[params.links.list3.link]]
        text = "Link Two"
        url = "#"

      [[params.links.list3.link]]
        text = "Link Three"
        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-src https://www.youtube.com/embed/; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
